#define WIFI_SSID "YOUR_WIFI_SSID"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"

#define MQTT_SERVER "BROKER_SERVER_IP"
#define MQTT_PORT 1883
char MQTT_TOPIC[] = "smart_zero/PASTE_YOUR_DEVICE_ID_HERE";
